@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindOrderCommandParser" as FindOrderCommandParser LOGIC_COLOR
participant ":FindOrderCommand" as FindOrderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findo n/Alex")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("findo n/Alex")
activate AddressBookParser

create FindOrderCommandParser
AddressBookParser -> FindOrderCommandParser
activate FindOrderCommandParser

FindOrderCommandParser --> AddressBookParser
deactivate FindOrderCommandParser

AddressBookParser --> FindOrderCommandParser : parse("findo n/Alex")


activate FindOrderCommandParser
create FindOrderCommand
FindOrderCommandParser --> FindOrderCommand
activate FindOrderCommand

FindOrderCommand --> FindOrderCommandParser : f
deactivate FindOrderCommand

FindOrderCommandParser --> AddressBookParser : f
deactivate FindOrderCommandParser
FindOrderCommandParser -[hidden]-> AddressBookParser
destroy FindOrderCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FindOrderCommand : execute()
activate FindOrderCommand

FindOrderCommand -> Model : updateFilteredOrderList(Predicate)

activate Model
Model --> FindOrderCommand
deactivate Model

create CommandResult
FindOrderCommand -> CommandResult
activate CommandResult

CommandResult --> FindOrderCommand
deactivate CommandResult

FindOrderCommand  --> LogicManager : result
deactivate FindOrderCommand

[<--LogicManager
deactivate LogicManager
@enduml
